### ISSUE TITLE
New discord link

### ISSUE THREAD

**Issue by daffysnuts** [youlinkoperatingsystem/scam#62]
the vanity link is not working

**Comment by ulnk** [comment]
https://discord.gg/skidsupport

**Comment by ulnk** [comment]
https://discord.gg/carterlam

**Comment by boumco** [comment]
new please

**Comment by ulnk** [comment]
https://discord.gg/blacklivesmatter2

**Comment by ulnk** [comment]
https://discord.gg/fortnite-lives-matter-996698905725116487
